# Generated by Django 4.1.5 on 2023-02-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('SourceLat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('SourceLon', models.DecimalField(decimal_places=15, max_digits=20)),
                ('DestinationLat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('DestinationLon', models.DecimalField(decimal_places=15, max_digits=20)),
                ('RideDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=30)),
                ('SourceLat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('SourceLon', models.DecimalField(decimal_places=15, max_digits=20)),
                ('DestinationLat', models.DecimalField(decimal_places=15, max_digits=20)),
                ('DestinationLon', models.DecimalField(decimal_places=15, max_digits=20)),
                ('RideDate', models.DateTimeField()),
            ],
        ),
    ]
