# Generated by Django 4.1.5 on 2023-02-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='Rider',
            new_name='Driver',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='fare',
        ),
        migrations.AddField(
            model_name='notification',
            name='Fare',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
